export const experienceList = [
  {
    company: "Globant",
    position: "Frontend Developer Intern",
    startDate: "July 2024",
    endDate: "October 2024",
    location: "Tucumán, Argentina (Remote)",
    description: [
      "- Designed and led the implementation of a scalable architecture for the Gloobcamp project, which allowed flexibility in adding new functionality and a solid foundation for future developments.",
      "- Trained team members in the advanced use of Next.js and TypeScript, achieving a 50% increase in their ability to solve problems autonomously.",
      "- Led the refactoring of key components, achieving a 30% improvement in project loading speed and a Lighthouse score of over 95% in performance and accessibility.",
      "- Coordinated the planning and execution of sprints to develop an iterative MVP, achieving timely deliveries in each project phase.",
    ],
    technologies: [
      "React",
      "Next.js",
      "Nest.js",
      "TypeScript",
      "JavaScript",
      "C",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "MySQL",
      "Supabase",
      "Firebase",
      "GraphQL",
      "Redux",
      "Apollo Client",
      "JWT",
      "Storybook",
      "Sass",
      "Astro",
      "Git",
      "GitHub",
      "Jest",
      "React Testing Library",
      "Webpack",
      "ESLint",
      "Docker",
      "Prepros",
      "CI/CD",
      "Lighthouse",
      "Google Analytics",
      "PageSpeed Insights",
      "Figma",
      "Agile",
      "Scrum",
    ],
    softSkills: [
      "Leadership",
      "Problem Solving",
      "Communication",
      "Attention to Detail",
      "Adaptability",
    ],
  },
  // {
  //   company: "INFOCOR MULTIMEDIA SL",
  //   position: "Frontend Developer",
  //   startDate: "2022",
  //   endDate: "2024",
  //   location: "Spain (Remote)",
  //   description: [
  //     "- Delivered high-quality code on time for client-facing projects, consistently meeting deadlines and project requirements, leading to +90% client satisfaction and increased repeat business.",
  //     "- Developed modular and reusable front-end architectures, streamlining the development process and reducing code duplication by 40%, which improved maintainability and scalability.",
  //     "- Contributed to the development of scalable APIs using Node.js and Express.js, enabling real-time data synchronization and seamless integration with front-end applications, enhancing app experience and user engagement.",
  //   ],
  //   technologies: [
  //     "Next.js",
  //     "Astro",
  //     "React",
  //     "Node.js",
  //     "Express.js",
  //     "MongoDB",
  //     "TypeScript",
  //     "JavaScript",
  //     "Supabase",
  //     "Firebase",
  //     "Strapi",
  //     "Git/GitHub",
  //     "Sass",
  //     "TailwindCSS",
  //     "Bootstrap",
  //   ],
  //   softSkills: [
  //     "Time Management",
  //     "Team Collaboration",
  //     "Problem Solving",
  //     "Adaptability",
  //     "Communication",
  //     "Attention to Detail",
  //   ],
  // },
];
