export const experienceList = [
  {
    company: "Independent",
    position: "Frontend Developer",
    startDate: "2022",
    endDate: "Present",
    description:
      "Built dynamic and responsive web applications using React, Astro, Next.js, Sass, and TailwindCSS while adhering to SOLID principles and DRY practices, resulting in a 30% reduction in technical debt. Optimized site performance and ensured WCAG compliance with tools like Lighthouse and PageSpeed Insights, improving page load speed by 25%. Co-led an agile team utilizing Trello to foster collaboration and achieve 100% on-time delivery of sprint goals throughout the project lifecycle. Implemented Jest unit tests for critical components and used Storybook to document reusable components, enhancing team efficiency in maintaining a scalable component library. Additionally, contributed to backend development tasks with Node.js, Express.js, MongoDB, Supabase, and Firebase.",
    technologies: [
      // Primary (most relevant and used)
      "Next.js",
      "Astro",
      "React",
      "TypeScript",
      "JavaScript",
      "Sass",
      "Less",
      "TailwindCSS",
      "Bootstrap",
      "Figma",
      "AdobeXD",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Firebase",
      "Supabase",
      // Secondary (tools or additional frameworks)
      "Team Collaboration",
      "Problem-Solving",
      "Adaptability",
      "Communication",
      "Time Management",
      "Leadership",
      // Tertiary (workflow, design, testing, project management)
      "Agile methodologies",
      "Trello",
      "Git/GitHub",
      "Web Accessibility",
      "Lighthouse",
      "Google Analytics",
      "Jest",
      "Storybook",
    ],
    softSkills: [
      "Communication",
      "Leadership & Mentorship",
      "Problem Solving",
      "Collaboration",
      "Organization & Planning",
      "User-Centered Approach",
      "Continuous Learning",
    ],
  },
];
