export const experienceList = [
  {
    company: "Globant",
    position: "Frontend Developer Intern",
    startDate: "July 2024",
    endDate: "October 2024",
    location: "Tucumán, Argentina (Remote)",
    description: [
      `- Led the code review process of the Intern Team, performing over 100 Pull Request reviews, identifying and addressing performance bottlenecks, and ensuring adherence to best practices, which improved code quality, reduced bugs by 20%, and enhanced project stability by 30%.`,
      "- Collaborated on the application's architecture, designing and implementing scalable, modular solutions and adhering to clean code principles, resulting in easier maintenance and enhanced long-term scalability of the platform.",
      "- Optimized site performance and accessibility by leveraging Lighthouse and Page Speed Insights, achieving a 35% improvement in page load speed, improving mobile performance by 20%, and ensuring WCAG 2.1 compliance to enhance usability for all users.",
    ],
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "TailwindCSS",
      "Git/GitHub",
    ],
    softSkills: [
      "Leadership",
      "Problem Solving",
      "Communication",
      "Attention to Detail",
      "Adaptability",
    ],
  },
  {
    company: "INFOCOR MULTIMEDIA SL",
    position: "Frontend Developer",
    startDate: "2022",
    endDate: "2024",
    location: "Spain (Remote)",
    description: [
      "- Delivered high-quality code on time for client-facing projects, consistently meeting deadlines and project requirements, leading to +90% client satisfaction and increased repeat business.",
      "- Developed modular and reusable front-end architectures, streamlining the development process and reducing code duplication by 40%, which improved maintainability and scalability.",
      "- Contributed to the development of scalable APIs using Node.js and Express.js, enabling real-time data synchronization and seamless integration with front-end applications, enhancing app experience and user engagement.",
    ],
    technologies: [
      "Next.js",
      "Astro",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "TypeScript",
      "JavaScript",
      "Supabase",
      "Firebase",
      "Strapi",
      "Git/GitHub",
      "Sass",
      "TailwindCSS",
      "Bootstrap",
    ],
    softSkills: [
      "Time Management",
      "Team Collaboration",
      "Problem Solving",
      "Adaptability",
      "Communication",
      "Attention to Detail",
    ],
  },
];
